steps:
- name: node:12.16.2
  entrypoint: npm
  args: ['install']

- name: node:12.16.2
  entrypoint: npm
  args: ['test']

- name: node:12.16.2
  entrypoint: npm
  args: ['run', 'build']

- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']